"""following

Revision ID: 95500ff5d7ec
Revises: 13a6fdb4b2db
Create Date: 2021-05-23 14:20:36.217665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95500ff5d7ec'
down_revision = '13a6fdb4b2db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followee_to_follower',
    sa.Column('followee_id', sa.Integer(), nullable=True),
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followee_to_follower')
    # ### end Alembic commands ###
