// constants
const SET_USER = "session/SET_USER";
const REMOVE_USER = "session/REMOVE_USER";
const ALL_CHARACTERS = "characters/ALL_CHARACTERS"
const NEXT_CARD = "loader/NEXT_CARD";
const RESET_CARDS = "loader/RESET_CARDS";
const GET_SINGLE_CARD = "loader/GET_SINGLE_CARD";
const SEARCH_PUB_CHARACTERS = "characters/SEARCH_PUB_CHARACTERS";
const SEARCH_TRIGGERED = "characters/SEARCH_TRIGGERED";
const CLEAR_SEARCH_PUB_CHARS = "characters/CLEAR_SEARCH_PUB_CHARS";


export {
  SET_USER,
  REMOVE_USER,
  ALL_CHARACTERS,
  NEXT_CARD,
  RESET_CARDS,
  GET_SINGLE_CARD,
  SEARCH_PUB_CHARACTERS,
  SEARCH_TRIGGERED,
  CLEAR_SEARCH_PUB_CHARS,


}
