// constants
const SET_USER = "session/SET_USER";
const REMOVE_USER = "session/REMOVE_USER";
const ALL_CHARACTERS = "characters/ALL_CHARACTERS"
const NEXT_CARD = "loader/NEXT_CARD";
const RESET_CARDS = "loader/RESET_CARDS";
const GET_SINGLE_CARD = "loader/GET_SINGLE_CARD";
const SEARCH_PUB_CHARACTERS = "characters/SEARCH_PUB_CHARACTERS";
const SEARCH_TRIGGERED = "characters/SEARCH_TRIGGERED";
const CLEAR_SEARCH_PUB_CHARS = "characters/CLEAR_SEARCH_PUB_CHARS";
const DELETE_USERS_PUB_CHARS = "characters/DELETE_USERS_PUB_CHARS";
const GET_USERS_BOOKS = "books/GET_USERS_BOOKS";
const GET_USERS_PRI_CHARS = "books/GET_USERS_PRI_CHARS";
const GET_USERS_PAGES = "books/GET_USERS_PAGES";
const DELETE_BOOK = "books/DELETE_BOOK";
const DELETE_USERS_PRI_CHARS = 'characters/DELETE_USERS_PRI_CHARS'
const DELETE_USERS_PAGE = 'books/DELETE_USERS_PAGE';


// for the modals here
const SHOW_MODAL = 'modal/SHOW_MODAL';
const HIDE_MODAL = 'modal/HIDE_MODAL';
const CONTENT_MODAL = "modal/CONTENT_MODAL";

// for the HomeLoader component
const SHOW_LOADER = "loader/SHOW_LOADER";
const HIDE_LOADER = "loader/HIDE_LOADER";





export {
  SET_USER,
  REMOVE_USER,
  ALL_CHARACTERS,
  NEXT_CARD,
  RESET_CARDS,
  GET_SINGLE_CARD,
  SEARCH_PUB_CHARACTERS,
  SEARCH_TRIGGERED,
  CLEAR_SEARCH_PUB_CHARS,
  DELETE_USERS_PUB_CHARS,
  GET_USERS_BOOKS,
  GET_USERS_PRI_CHARS,
  GET_USERS_PAGES,
  DELETE_BOOK,
  SHOW_MODAL,
  HIDE_MODAL,
  DELETE_USERS_PRI_CHARS,
  DELETE_USERS_PAGE,
  SHOW_LOADER,
  HIDE_LOADER,
  CONTENT_MODAL,


}
